# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release
run-name: 'v${{ github.event.inputs.version }}'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        type: string

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'v${{ github.event.inputs.version }}'
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Build
      run: make build ver='${{ github.event.inputs.version }}'
    - name: Test
      run: make test
    - name: Tar Archive
      run: tar -zcvf hb-linux-amd64-${{ github.event.inputs.version }}.tar.gz bin

    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        tag: 'v${{ github.event.inputs.version }}'
        draft: true
        prerelease: true
        artifacts: "hb-linux-amd64-${{ github.event.inputs.version }}.tar.gz"

  docker:
    runs-on: ubunut-latest
    needs: build-amd64
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'v${{ github.event.inputs.version }}'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: true
        tags: meeron/honey-badger:latest,meeron/honey-badger:${{ github.event.inputs.version }}
        build-args: |
          ver:${{ github.event.inputs.version }}
